// <auto-generated />
namespace _2_1_2015_WSite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedPostedDatetoCommSentTo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPostedDatetoCommSentTo));
        
        string IMigrationMetadata.Id
        {
            get { return "201502021922531_added PostedDate to CommSentTo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
