// <auto-generated />
namespace _2_1_2015_WSite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Allowpubdataandunpubdatetobenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Allowpubdataandunpubdatetobenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201601061957446_Allow pubdata and unpubdate to be nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
